### ISSUE TITLE
low level production networking tools should not include surveillance 

### ISSUE THREAD

**Issue by sneak** [DefinedNet/mobile_nebula#199]
https://github.com/DefinedNet/mobile_nebula/commit/1ea8438a5d6fbd64311e39cfd82a45548e107562

This application now includes nonconsensual surveillance in the form of Sentry reporting. Thank you for including notice in the changelog so that I could uninstall it. 

It is insane that you think that this sort of nonconsensual, opt-out surveillance is acceptable in enterprise software.

**Comment by johnmaguire** [comment]
Hi @sneak, thanks for the feedback. Mobile Nebula is proprietary software produced by Defined Networking. We include Sentry in the mobile app in order to monitor and improve app stability. We'll investigate adding an opt-out option for Sentry to the app (#200). That said, we do not include personally identifiable information in crash reports. Please see our data privacy policy on the [App Store](https://apps.apple.com/us/app/mobile-nebula/id1509587936) / [Play Store](https://play.google.com/store/apps/datasafety?id=net.defined.mobile_nebula) for more details. All the best.
