### ISSUE TITLE
Improve public key export / private key import

### ISSUE THREAD

**Issue by JohnMaguire** [DefinedNet/mobile_nebula#48]
I just setup Nebula on an Android device and hit an annoyance during the pubkey export / private key import dance. It seems as though the private keys are refreshed when the screen is loaded. In my case, the device turned the screen off due to inactivity while I was generating a certificate on my computer. When I turned the phone screen back on, the keypair had changed and I had to do the dance again, making sure my phone screen stayed on.

There is a second issue that makes this a little more frustrating: The certificate is not validated against the private key until you save the entire site configuration. Then there's an error reported in the site list view, and going back to site config explains the issue.

Furthermore, since pub/privkey validation doesn't happen until the entire site is saved it may seem as though you're receiving the error again after correcting the issue.

**Comment by xxxserxxx** [comment]
So, to clarify what I think this request is -- it'd be much easier for users to import both the priv key & cert, rather than having the mobile app generate a private key that the user must sign. That way, the workflow would be similar to the tutorial desktop flow: generate both on the lighthouse, copy both over to the client, import (or, on desktop, reference) them.

Can we have an "choose private key file" alternative to the "share public key" widget?

**Comment by nbrownus** [comment]
Importing a private key is #20 

The request here is:
1. Validate the public key against the private at the time the public key is imported.
2. Do not regenerate the private key each time the page is rebuilt.
